<!DOCTYPE html>
<html lang="en">
      <head>
        <meta charset="utf-8">
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="js/menu-highlighter.js"></script>
        <title>HOME</title>
        <link rel="stylesheet" type="text/css" href="css/navigation.css">
        <link rel="stylesheet" type="text/css" href="a3css/styles.css">
        <link rel="stylesheet" href="sss/sss.css">
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <link href="https://fonts.googleapis.com/css?family=Bellefair" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display:900" rel="stylesheet">
      </head>
      <body>
        <header>
            <h1><a href="index.php">Students of CSC 174</a></h1>
        </header>
      <!-- Navigation bar -->
        <?php include "nav.inc";?>
