<!DOCTYPE html>
<html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Students of CSC174</title>

        <link rel="stylesheet" type="text/css" href="css/styles.css">
        <link rel="stylesheet" href="css/sss.css">
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        
        <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Changa" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Bubblegum+Sans" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
      </head>
      <body>
        <header>
            <h1><a href="index.php">Students of CSC 174</a></h1>
        </header>
      <!-- Navigation bar -->
        <?php include "nav.inc";?>
