<nav class = "navbar">
	<ul>
		<li><a href="index.php">Home</a></li>
		<div class="dropdown">
			<button class="dropbtn">Tennis Players</button>
			  <div class="dropdown-content">
			    <a href="alex.php">Alexander Punj</a>
			    <a href="masaru.php">Masaru Fujimaki</a>
			    <a href="matt.php">Matt Reskinoff</a>
			  </div>
		</div>
		<div class="dropdown">
			<button class="dropbtn">Professionals</button>
			  <div class="dropdown-content">
			    <a href="zubair.php">Zubair Aziz</a>
			  </div>
		</div>
		<li><a href="form.php">Leave Some Feedback?</a></li>
	</ul>
</nav>
